-- ===========================================================================
-- haifuraiya_coeffs_pkg.vhd
--
-- AUTO-GENERATED by docs/polyphase_channelizer.ipynb -- do not edit by hand.
-- Regenerate by re-running the notebook.
--
-- Prototype filter coefficients for the Haifuraiya channelizer.
-- Branch-major layout: branch k owns 1D indices
--   k*TAPS_PER_BRANCH .. (k+1)*TAPS_PER_BRANCH - 1
--
-- Configuration:
--   Channels:        64
--   Taps per branch: 24
--   Total taps:      1536
--   Format:          Q1.14 signed 16-bit
--
-- Why this exists alongside the .hex file: synth working directory != IP
-- source directory, so file_open at elaboration time cannot find the .hex.
-- Compiling the data in as a constant array sidesteps the issue.
-- ===========================================================================

library ieee;
use ieee.std_logic_1164.all;

package haifuraiya_coeffs_pkg is

    constant COEFF_WIDTH  : positive := 16;
    constant N_TOTAL_TAPS : natural  := 1536;

    type coeff_rom_t is array (natural range <>)
                       of std_logic_vector(COEFF_WIDTH - 1 downto 0);

    constant ALL_COEFFS : coeff_rom_t(0 to N_TOTAL_TAPS - 1) := (
        x"FFFB", x"FFFE", x"0004", x"FFFF", x"0001", x"0003", x"FFFA", x"000B",  -- branch 0, taps 0..7
        x"FFEF", x"0017", x"FFE4", x"0020", x"00D9", x"001C", x"FFE6", x"0016",  -- branch 0, taps 8..15
        x"FFEF", x"000C", x"FFFA", x"0003", x"0001", x"FFFF", x"0004", x"FFFE",  -- branch 0, taps 16..23
        x"FFFF", x"FFFE", x"0005", x"FFFF", x"0002", x"0002", x"FFFB", x"000B",  -- branch 1, taps 0..7
        x"FFEF", x"0017", x"FFE3", x"0024", x"00D9", x"0019", x"FFE7", x"0016",  -- branch 1, taps 8..15
        x"FFEF", x"000C", x"FFFA", x"0003", x"0001", x"FFFF", x"0004", x"FFFE",  -- branch 1, taps 16..23
        x"FFFF", x"FFFE", x"0005", x"FFFF", x"0002", x"0002", x"FFFB", x"000B",  -- branch 2, taps 0..7
        x"FFEF", x"0018", x"FFE2", x"0027", x"00D9", x"0016", x"FFE8", x"0015",  -- branch 2, taps 8..15
        x"FFEF", x"000C", x"FFF9", x"0003", x"0001", x"0000", x"0004", x"FFFE",  -- branch 2, taps 16..23
        x"FFFF", x"FFFE", x"0005", x"FFFF", x"0002", x"0002", x"FFFB", x"000B",  -- branch 3, taps 0..7
        x"FFEF", x"0018", x"FFE0", x"002B", x"00D9", x"0012", x"FFEA", x"0015",  -- branch 3, taps 8..15
        x"FFF0", x"000C", x"FFF9", x"0004", x"0001", x"0000", x"0004", x"FFFE",  -- branch 3, taps 16..23
        x"FFFF", x"FFFE", x"0005", x"FFFE", x"0002", x"0001", x"FFFB", x"000B",  -- branch 4, taps 0..7
        x"FFEF", x"0019", x"FFDF", x"002F", x"00D8", x"000F", x"FFEB", x"0014",  -- branch 4, taps 8..15
        x"FFF0", x"000C", x"FFF9", x"0004", x"0000", x"0000", x"0004", x"FFFE",  -- branch 4, taps 16..23
        x"FFFF", x"FFFE", x"0005", x"FFFE", x"0002", x"0001", x"FFFC", x"000A",  -- branch 5, taps 0..7
        x"FFEF", x"0019", x"FFDE", x"0033", x"00D7", x"000C", x"FFED", x"0013",  -- branch 5, taps 8..15
        x"FFF0", x"000C", x"FFF9", x"0004", x"0000", x"0000", x"0004", x"FFFE",  -- branch 5, taps 16..23
        x"FFFF", x"FFFE", x"0005", x"FFFE", x"0003", x"0001", x"FFFC", x"000A",  -- branch 6, taps 0..7
        x"FFEF", x"0019", x"FFDD", x"0037", x"00D7", x"0008", x"FFEE", x"0013",  -- branch 6, taps 8..15
        x"FFF0", x"000C", x"FFF9", x"0004", x"0000", x"0000", x"0004", x"FFFE",  -- branch 6, taps 16..23
        x"FFFF", x"FFFE", x"0005", x"FFFE", x"0003", x"0000", x"FFFC", x"000A",  -- branch 7, taps 0..7
        x"FFF0", x"0019", x"FFDC", x"003B", x"00D6", x"0005", x"FFF0", x"0012",  -- branch 7, taps 8..15
        x"FFF1", x"000C", x"FFF9", x"0005", x"0000", x"0000", x"0004", x"FFFE",  -- branch 7, taps 16..23
        x"FFFF", x"FFFE", x"0005", x"FFFE", x"0003", x"0000", x"FFFD", x"0009",  -- branch 8, taps 0..7
        x"FFF0", x"001A", x"FFDB", x"003F", x"00D5", x"0002", x"FFF1", x"0011",  -- branch 8, taps 8..15
        x"FFF1", x"000C", x"FFF8", x"0005", x"FFFF", x"0001", x"0004", x"FFFD",  -- branch 8, taps 16..23
        x"FFFF", x"FFFE", x"0005", x"FFFE", x"0003", x"0000", x"FFFD", x"0009",  -- branch 9, taps 0..7
        x"FFF0", x"001A", x"FFDA", x"0042", x"00D3", x"FFFF", x"FFF3", x"0010",  -- branch 9, taps 8..15
        x"FFF1", x"000C", x"FFF8", x"0005", x"FFFF", x"0001", x"0003", x"FFFD",  -- branch 9, taps 16..23
        x"FFFF", x"FFFE", x"0005", x"FFFE", x"0004", x"0000", x"FFFE", x"0009",  -- branch 10, taps 0..7
        x"FFF0", x"001A", x"FFD9", x"0046", x"00D2", x"FFFC", x"FFF4", x"000F",  -- branch 10, taps 8..15
        x"FFF2", x"000C", x"FFF8", x"0005", x"FFFF", x"0001", x"0003", x"FFFD",  -- branch 10, taps 16..23
        x"FFFF", x"FFFE", x"0005", x"FFFE", x"0004", x"FFFF", x"FFFE", x"0008",  -- branch 11, taps 0..7
        x"FFF0", x"001A", x"FFD8", x"004B", x"00D1", x"FFFA", x"FFF6", x"000F",  -- branch 11, taps 8..15
        x"FFF2", x"000C", x"FFF8", x"0005", x"FFFF", x"0001", x"0003", x"FFFD",  -- branch 11, taps 16..23
        x"FFFF", x"FFFE", x"0005", x"FFFD", x"0004", x"FFFF", x"FFFE", x"0008",  -- branch 12, taps 0..7
        x"FFF1", x"001A", x"FFD7", x"004F", x"00CF", x"FFF7", x"FFF7", x"000E",  -- branch 12, taps 8..15
        x"FFF2", x"000C", x"FFF8", x"0006", x"FFFF", x"0001", x"0003", x"FFFD",  -- branch 12, taps 16..23
        x"FFFF", x"FFFF", x"0005", x"FFFD", x"0004", x"FFFF", x"FFFF", x"0007",  -- branch 13, taps 0..7
        x"FFF1", x"001A", x"FFD6", x"0053", x"00CD", x"FFF4", x"FFF9", x"000D",  -- branch 13, taps 8..15
        x"FFF3", x"000C", x"FFF8", x"0006", x"FFFF", x"0001", x"0003", x"FFFD",  -- branch 13, taps 16..23
        x"FFFF", x"FFFF", x"0005", x"FFFD", x"0004", x"FFFE", x"FFFF", x"0007",  -- branch 14, taps 0..7
        x"FFF1", x"001A", x"FFD5", x"0057", x"00CC", x"FFF2", x"FFFA", x"000C",  -- branch 14, taps 8..15
        x"FFF3", x"000C", x"FFF8", x"0006", x"FFFE", x"0002", x"0003", x"FFFD",  -- branch 14, taps 16..23
        x"FFFF", x"FFFF", x"0005", x"FFFD", x"0005", x"FFFE", x"0000", x"0006",  -- branch 15, taps 0..7
        x"FFF2", x"001A", x"FFD5", x"005B", x"00CA", x"FFEF", x"FFFC", x"000B",  -- branch 15, taps 8..15
        x"FFF4", x"000B", x"FFF8", x"0006", x"FFFE", x"0002", x"0003", x"FFFE",  -- branch 15, taps 16..23
        x"FFFF", x"FFFF", x"0005", x"FFFD", x"0005", x"FFFE", x"0000", x"0006",  -- branch 16, taps 0..7
        x"FFF2", x"001A", x"FFD4", x"005F", x"00C8", x"FFED", x"FFFD", x"000A",  -- branch 16, taps 8..15
        x"FFF4", x"000B", x"FFF8", x"0006", x"FFFE", x"0002", x"0003", x"FFFE",  -- branch 16, taps 16..23
        x"FFFF", x"FFFF", x"0005", x"FFFD", x"0005", x"FFFD", x"0000", x"0005",  -- branch 17, taps 0..7
        x"FFF3", x"0019", x"FFD4", x"0063", x"00C5", x"FFEB", x"FFFF", x"0009",  -- branch 17, taps 8..15
        x"FFF5", x"000B", x"FFF8", x"0006", x"FFFE", x"0002", x"0002", x"FFFE",  -- branch 17, taps 16..23
        x"FFFF", x"FFFF", x"0005", x"FFFD", x"0005", x"FFFD", x"0001", x"0005",  -- branch 18, taps 0..7
        x"FFF3", x"0019", x"FFD3", x"0067", x"00C3", x"FFE9", x"0000", x"0009",  -- branch 18, taps 8..15
        x"FFF5", x"000B", x"FFF8", x"0006", x"FFFE", x"0002", x"0002", x"FFFE",  -- branch 18, taps 16..23
        x"FFFF", x"FFFF", x"0005", x"FFFD", x"0005", x"FFFD", x"0001", x"0004",  -- branch 19, taps 0..7
        x"FFF4", x"0019", x"FFD3", x"006B", x"00C1", x"FFE7", x"0002", x"0008",  -- branch 19, taps 8..15
        x"FFF6", x"000B", x"FFF8", x"0006", x"FFFE", x"0002", x"0002", x"FFFE",  -- branch 19, taps 16..23
        x"FFFF", x"FFFF", x"0005", x"FFFD", x"0005", x"FFFC", x"0002", x"0004",  -- branch 20, taps 0..7
        x"FFF4", x"0018", x"FFD2", x"006F", x"00BE", x"FFE5", x"0003", x"0007",  -- branch 20, taps 8..15
        x"FFF6", x"000A", x"FFF8", x"0006", x"FFFE", x"0003", x"0002", x"FFFE",  -- branch 20, taps 16..23
        x"FFFE", x"FFFF", x"0005", x"FFFD", x"0006", x"FFFC", x"0002", x"0003",  -- branch 21, taps 0..7
        x"FFF5", x"0018", x"FFD2", x"0073", x"00BC", x"FFE3", x"0004", x"0006",  -- branch 21, taps 8..15
        x"FFF7", x"000A", x"FFF8", x"0007", x"FFFD", x"0003", x"0002", x"FFFE",  -- branch 21, taps 16..23
        x"FFFE", x"FFFF", x"0005", x"FFFD", x"0006", x"FFFC", x"0003", x"0003",  -- branch 22, taps 0..7
        x"FFF6", x"0017", x"FFD2", x"0077", x"00B9", x"FFE1", x"0006", x"0005",  -- branch 22, taps 8..15
        x"FFF7", x"000A", x"FFF8", x"0007", x"FFFD", x"0003", x"0002", x"FFFE",  -- branch 22, taps 16..23
        x"FFFE", x"FFFF", x"0005", x"FFFD", x"0006", x"FFFC", x"0003", x"0002",  -- branch 23, taps 0..7
        x"FFF6", x"0017", x"FFD2", x"007B", x"00B6", x"FFDF", x"0007", x"0004",  -- branch 23, taps 8..15
        x"FFF8", x"000A", x"FFF8", x"0007", x"FFFD", x"0003", x"0002", x"FFFE",  -- branch 23, taps 16..23
        x"FFFE", x"0000", x"0005", x"FFFD", x"0006", x"FFFB", x"0003", x"0002",  -- branch 24, taps 0..7
        x"FFF7", x"0016", x"FFD2", x"007F", x"00B3", x"FFDE", x"0008", x"0003",  -- branch 24, taps 8..15
        x"FFF8", x"0009", x"FFF8", x"0007", x"FFFD", x"0003", x"0002", x"FFFE",  -- branch 24, taps 16..23
        x"FFFE", x"0000", x"0005", x"FFFD", x"0006", x"FFFB", x"0004", x"0001",  -- branch 25, taps 0..7
        x"FFF8", x"0016", x"FFD2", x"0083", x"00B0", x"FFDC", x"0009", x"0002",  -- branch 25, taps 8..15
        x"FFF9", x"0009", x"FFF8", x"0007", x"FFFD", x"0003", x"0001", x"FFFE",  -- branch 25, taps 16..23
        x"FFFE", x"0000", x"0005", x"FFFD", x"0006", x"FFFB", x"0004", x"0000",  -- branch 26, taps 0..7
        x"FFF8", x"0015", x"FFD2", x"0087", x"00AD", x"FFDB", x"000B", x"0001",  -- branch 26, taps 8..15
        x"FFFA", x"0009", x"FFF9", x"0007", x"FFFD", x"0003", x"0001", x"FFFE",  -- branch 26, taps 16..23
        x"FFFE", x"0000", x"0005", x"FFFC", x"0006", x"FFFA", x"0005", x"0000",  -- branch 27, taps 0..7
        x"FFF9", x"0014", x"FFD3", x"008A", x"00AA", x"FFDA", x"000C", x"0000",  -- branch 27, taps 8..15
        x"FFFA", x"0008", x"FFF9", x"0007", x"FFFD", x"0004", x"0001", x"FFFE",  -- branch 27, taps 16..23
        x"FFFE", x"0000", x"0004", x"FFFC", x"0006", x"FFFA", x"0005", x"FFFF",  -- branch 28, taps 0..7
        x"FFFA", x"0013", x"FFD3", x"008E", x"00A7", x"FFD9", x"000D", x"FFFF",  -- branch 28, taps 8..15
        x"FFFB", x"0008", x"FFF9", x"0007", x"FFFD", x"0004", x"0001", x"FFFE",  -- branch 28, taps 16..23
        x"FFFE", x"0000", x"0004", x"FFFD", x"0006", x"FFFA", x"0006", x"FFFF",  -- branch 29, taps 0..7
        x"FFFB", x"0013", x"FFD4", x"0092", x"00A4", x"FFD7", x"000E", x"FFFF",  -- branch 29, taps 8..15
        x"FFFB", x"0008", x"FFF9", x"0007", x"FFFD", x"0004", x"0001", x"FFFE",  -- branch 29, taps 16..23
        x"FFFE", x"0000", x"0004", x"FFFD", x"0007", x"FFFA", x"0006", x"FFFE",  -- branch 30, taps 0..7
        x"FFFB", x"0012", x"FFD4", x"0096", x"00A0", x"FFD7", x"000F", x"FFFE",  -- branch 30, taps 8..15
        x"FFFC", x"0007", x"FFF9", x"0007", x"FFFD", x"0004", x"0001", x"FFFE",  -- branch 30, taps 16..23
        x"FFFE", x"0000", x"0004", x"FFFD", x"0007", x"FFFA", x"0006", x"FFFD",  -- branch 31, taps 0..7
        x"FFFC", x"0011", x"FFD5", x"0099", x"009D", x"FFD6", x"0010", x"FFFD",  -- branch 31, taps 8..15
        x"FFFD", x"0007", x"FFF9", x"0007", x"FFFD", x"0004", x"0001", x"FFFE",  -- branch 31, taps 16..23
        x"FFFE", x"0001", x"0004", x"FFFD", x"0007", x"FFF9", x"0007", x"FFFD",  -- branch 32, taps 0..7
        x"FFFD", x"0010", x"FFD6", x"009D", x"0099", x"FFD5", x"0011", x"FFFC",  -- branch 32, taps 8..15
        x"FFFD", x"0006", x"FFFA", x"0007", x"FFFD", x"0004", x"0000", x"FFFE",  -- branch 32, taps 16..23
        x"FFFE", x"0001", x"0004", x"FFFD", x"0007", x"FFF9", x"0007", x"FFFC",  -- branch 33, taps 0..7
        x"FFFE", x"000F", x"FFD7", x"00A0", x"0096", x"FFD4", x"0012", x"FFFB",  -- branch 33, taps 8..15
        x"FFFE", x"0006", x"FFFA", x"0007", x"FFFD", x"0004", x"0000", x"FFFE",  -- branch 33, taps 16..23
        x"FFFE", x"0001", x"0004", x"FFFD", x"0007", x"FFF9", x"0008", x"FFFB",  -- branch 34, taps 0..7
        x"FFFF", x"000E", x"FFD7", x"00A4", x"0092", x"FFD4", x"0013", x"FFFB",  -- branch 34, taps 8..15
        x"FFFF", x"0006", x"FFFA", x"0006", x"FFFD", x"0004", x"0000", x"FFFE",  -- branch 34, taps 16..23
        x"FFFE", x"0001", x"0004", x"FFFD", x"0007", x"FFF9", x"0008", x"FFFB",  -- branch 35, taps 0..7
        x"FFFF", x"000D", x"FFD9", x"00A7", x"008E", x"FFD3", x"0013", x"FFFA",  -- branch 35, taps 8..15
        x"FFFF", x"0005", x"FFFA", x"0006", x"FFFC", x"0004", x"0000", x"FFFE",  -- branch 35, taps 16..23
        x"FFFE", x"0001", x"0004", x"FFFD", x"0007", x"FFF9", x"0008", x"FFFA",  -- branch 36, taps 0..7
        x"0000", x"000C", x"FFDA", x"00AA", x"008A", x"FFD3", x"0014", x"FFF9",  -- branch 36, taps 8..15
        x"0000", x"0005", x"FFFA", x"0006", x"FFFC", x"0005", x"0000", x"FFFE",  -- branch 36, taps 16..23
        x"FFFE", x"0001", x"0003", x"FFFD", x"0007", x"FFF9", x"0009", x"FFFA",  -- branch 37, taps 0..7
        x"0001", x"000B", x"FFDB", x"00AD", x"0087", x"FFD2", x"0015", x"FFF8",  -- branch 37, taps 8..15
        x"0000", x"0004", x"FFFB", x"0006", x"FFFD", x"0005", x"0000", x"FFFE",  -- branch 37, taps 16..23
        x"FFFE", x"0001", x"0003", x"FFFD", x"0007", x"FFF8", x"0009", x"FFF9",  -- branch 38, taps 0..7
        x"0002", x"0009", x"FFDC", x"00B0", x"0083", x"FFD2", x"0016", x"FFF8",  -- branch 38, taps 8..15
        x"0001", x"0004", x"FFFB", x"0006", x"FFFD", x"0005", x"0000", x"FFFE",  -- branch 38, taps 16..23
        x"FFFE", x"0002", x"0003", x"FFFD", x"0007", x"FFF8", x"0009", x"FFF8",  -- branch 39, taps 0..7
        x"0003", x"0008", x"FFDE", x"00B3", x"007F", x"FFD2", x"0016", x"FFF7",  -- branch 39, taps 8..15
        x"0002", x"0003", x"FFFB", x"0006", x"FFFD", x"0005", x"0000", x"FFFE",  -- branch 39, taps 16..23
        x"FFFE", x"0002", x"0003", x"FFFD", x"0007", x"FFF8", x"000A", x"FFF8",  -- branch 40, taps 0..7
        x"0004", x"0007", x"FFDF", x"00B6", x"007B", x"FFD2", x"0017", x"FFF6",  -- branch 40, taps 8..15
        x"0002", x"0003", x"FFFC", x"0006", x"FFFD", x"0005", x"FFFF", x"FFFE",  -- branch 40, taps 16..23
        x"FFFE", x"0002", x"0003", x"FFFD", x"0007", x"FFF8", x"000A", x"FFF7",  -- branch 41, taps 0..7
        x"0005", x"0006", x"FFE1", x"00B9", x"0077", x"FFD2", x"0017", x"FFF6",  -- branch 41, taps 8..15
        x"0003", x"0003", x"FFFC", x"0006", x"FFFD", x"0005", x"FFFF", x"FFFE",  -- branch 41, taps 16..23
        x"FFFE", x"0002", x"0003", x"FFFD", x"0007", x"FFF8", x"000A", x"FFF7",  -- branch 42, taps 0..7
        x"0006", x"0004", x"FFE3", x"00BC", x"0073", x"FFD2", x"0018", x"FFF5",  -- branch 42, taps 8..15
        x"0003", x"0002", x"FFFC", x"0006", x"FFFD", x"0005", x"FFFF", x"FFFE",  -- branch 42, taps 16..23
        x"FFFE", x"0002", x"0003", x"FFFE", x"0006", x"FFF8", x"000A", x"FFF6",  -- branch 43, taps 0..7
        x"0007", x"0003", x"FFE5", x"00BE", x"006F", x"FFD2", x"0018", x"FFF4",  -- branch 43, taps 8..15
        x"0004", x"0002", x"FFFC", x"0005", x"FFFD", x"0005", x"FFFF", x"FFFF",  -- branch 43, taps 16..23
        x"FFFE", x"0002", x"0002", x"FFFE", x"0006", x"FFF8", x"000B", x"FFF6",  -- branch 44, taps 0..7
        x"0008", x"0002", x"FFE7", x"00C1", x"006B", x"FFD3", x"0019", x"FFF4",  -- branch 44, taps 8..15
        x"0004", x"0001", x"FFFD", x"0005", x"FFFD", x"0005", x"FFFF", x"FFFF",  -- branch 44, taps 16..23
        x"FFFE", x"0002", x"0002", x"FFFE", x"0006", x"FFF8", x"000B", x"FFF5",  -- branch 45, taps 0..7
        x"0009", x"0000", x"FFE9", x"00C3", x"0067", x"FFD3", x"0019", x"FFF3",  -- branch 45, taps 8..15
        x"0005", x"0001", x"FFFD", x"0005", x"FFFD", x"0005", x"FFFF", x"FFFF",  -- branch 45, taps 16..23
        x"FFFE", x"0002", x"0002", x"FFFE", x"0006", x"FFF8", x"000B", x"FFF5",  -- branch 46, taps 0..7
        x"0009", x"FFFF", x"FFEB", x"00C5", x"0063", x"FFD4", x"0019", x"FFF3",  -- branch 46, taps 8..15
        x"0005", x"0000", x"FFFD", x"0005", x"FFFD", x"0005", x"FFFF", x"FFFF",  -- branch 46, taps 16..23
        x"FFFE", x"0003", x"0002", x"FFFE", x"0006", x"FFF8", x"000B", x"FFF4",  -- branch 47, taps 0..7
        x"000A", x"FFFD", x"FFED", x"00C8", x"005F", x"FFD4", x"001A", x"FFF2",  -- branch 47, taps 8..15
        x"0006", x"0000", x"FFFE", x"0005", x"FFFD", x"0005", x"FFFF", x"FFFF",  -- branch 47, taps 16..23
        x"FFFE", x"0003", x"0002", x"FFFE", x"0006", x"FFF8", x"000B", x"FFF4",  -- branch 48, taps 0..7
        x"000B", x"FFFC", x"FFEF", x"00CA", x"005B", x"FFD5", x"001A", x"FFF2",  -- branch 48, taps 8..15
        x"0006", x"0000", x"FFFE", x"0005", x"FFFD", x"0005", x"FFFF", x"FFFF",  -- branch 48, taps 16..23
        x"FFFD", x"0003", x"0002", x"FFFE", x"0006", x"FFF8", x"000C", x"FFF3",  -- branch 49, taps 0..7
        x"000C", x"FFFA", x"FFF2", x"00CC", x"0057", x"FFD5", x"001A", x"FFF1",  -- branch 49, taps 8..15
        x"0007", x"FFFF", x"FFFE", x"0004", x"FFFD", x"0005", x"FFFF", x"FFFF",  -- branch 49, taps 16..23
        x"FFFD", x"0003", x"0001", x"FFFF", x"0006", x"FFF8", x"000C", x"FFF3",  -- branch 50, taps 0..7
        x"000D", x"FFF9", x"FFF4", x"00CD", x"0053", x"FFD6", x"001A", x"FFF1",  -- branch 50, taps 8..15
        x"0007", x"FFFF", x"FFFF", x"0004", x"FFFD", x"0005", x"FFFF", x"FFFF",  -- branch 50, taps 16..23
        x"FFFD", x"0003", x"0001", x"FFFF", x"0006", x"FFF8", x"000C", x"FFF2",  -- branch 51, taps 0..7
        x"000E", x"FFF7", x"FFF7", x"00CF", x"004F", x"FFD7", x"001A", x"FFF1",  -- branch 51, taps 8..15
        x"0008", x"FFFE", x"FFFF", x"0004", x"FFFD", x"0005", x"FFFE", x"FFFF",  -- branch 51, taps 16..23
        x"FFFD", x"0003", x"0001", x"FFFF", x"0005", x"FFF8", x"000C", x"FFF2",  -- branch 52, taps 0..7
        x"000F", x"FFF6", x"FFFA", x"00D1", x"004B", x"FFD8", x"001A", x"FFF0",  -- branch 52, taps 8..15
        x"0008", x"FFFE", x"FFFF", x"0004", x"FFFE", x"0005", x"FFFE", x"FFFF",  -- branch 52, taps 16..23
        x"FFFD", x"0003", x"0001", x"FFFF", x"0005", x"FFF8", x"000C", x"FFF2",  -- branch 53, taps 0..7
        x"000F", x"FFF4", x"FFFC", x"00D2", x"0046", x"FFD9", x"001A", x"FFF0",  -- branch 53, taps 8..15
        x"0009", x"FFFE", x"0000", x"0004", x"FFFE", x"0005", x"FFFE", x"FFFF",  -- branch 53, taps 16..23
        x"FFFD", x"0003", x"0001", x"FFFF", x"0005", x"FFF8", x"000C", x"FFF1",  -- branch 54, taps 0..7
        x"0010", x"FFF3", x"FFFF", x"00D3", x"0042", x"FFDA", x"001A", x"FFF0",  -- branch 54, taps 8..15
        x"0009", x"FFFD", x"0000", x"0003", x"FFFE", x"0005", x"FFFE", x"FFFF",  -- branch 54, taps 16..23
        x"FFFD", x"0004", x"0001", x"FFFF", x"0005", x"FFF8", x"000C", x"FFF1",  -- branch 55, taps 0..7
        x"0011", x"FFF1", x"0002", x"00D5", x"003F", x"FFDB", x"001A", x"FFF0",  -- branch 55, taps 8..15
        x"0009", x"FFFD", x"0000", x"0003", x"FFFE", x"0005", x"FFFE", x"FFFF",  -- branch 55, taps 16..23
        x"FFFE", x"0004", x"0000", x"0000", x"0005", x"FFF9", x"000C", x"FFF1",  -- branch 56, taps 0..7
        x"0012", x"FFF0", x"0005", x"00D6", x"003B", x"FFDC", x"0019", x"FFF0",  -- branch 56, taps 8..15
        x"000A", x"FFFC", x"0000", x"0003", x"FFFE", x"0005", x"FFFE", x"FFFF",  -- branch 56, taps 16..23
        x"FFFE", x"0004", x"0000", x"0000", x"0004", x"FFF9", x"000C", x"FFF0",  -- branch 57, taps 0..7
        x"0013", x"FFEE", x"0008", x"00D7", x"0037", x"FFDD", x"0019", x"FFEF",  -- branch 57, taps 8..15
        x"000A", x"FFFC", x"0001", x"0003", x"FFFE", x"0005", x"FFFE", x"FFFF",  -- branch 57, taps 16..23
        x"FFFE", x"0004", x"0000", x"0000", x"0004", x"FFF9", x"000C", x"FFF0",  -- branch 58, taps 0..7
        x"0013", x"FFED", x"000C", x"00D7", x"0033", x"FFDE", x"0019", x"FFEF",  -- branch 58, taps 8..15
        x"000A", x"FFFC", x"0001", x"0002", x"FFFE", x"0005", x"FFFE", x"FFFF",  -- branch 58, taps 16..23
        x"FFFE", x"0004", x"0000", x"0000", x"0004", x"FFF9", x"000C", x"FFF0",  -- branch 59, taps 0..7
        x"0014", x"FFEB", x"000F", x"00D8", x"002F", x"FFDF", x"0019", x"FFEF",  -- branch 59, taps 8..15
        x"000B", x"FFFB", x"0001", x"0002", x"FFFE", x"0005", x"FFFE", x"FFFF",  -- branch 59, taps 16..23
        x"FFFE", x"0004", x"0000", x"0001", x"0004", x"FFF9", x"000C", x"FFF0",  -- branch 60, taps 0..7
        x"0015", x"FFEA", x"0012", x"00D9", x"002B", x"FFE0", x"0018", x"FFEF",  -- branch 60, taps 8..15
        x"000B", x"FFFB", x"0002", x"0002", x"FFFF", x"0005", x"FFFE", x"FFFF",  -- branch 60, taps 16..23
        x"FFFE", x"0004", x"0000", x"0001", x"0003", x"FFF9", x"000C", x"FFEF",  -- branch 61, taps 0..7
        x"0015", x"FFE8", x"0016", x"00D9", x"0027", x"FFE2", x"0018", x"FFEF",  -- branch 61, taps 8..15
        x"000B", x"FFFB", x"0002", x"0002", x"FFFF", x"0005", x"FFFE", x"FFFF",  -- branch 61, taps 16..23
        x"FFFE", x"0004", x"FFFF", x"0001", x"0003", x"FFFA", x"000C", x"FFEF",  -- branch 62, taps 0..7
        x"0016", x"FFE7", x"0019", x"00D9", x"0024", x"FFE3", x"0017", x"FFEF",  -- branch 62, taps 8..15
        x"000B", x"FFFB", x"0002", x"0002", x"FFFF", x"0005", x"FFFE", x"FFFF",  -- branch 62, taps 16..23
        x"FFFE", x"0004", x"FFFF", x"0001", x"0003", x"FFFA", x"000C", x"FFEF",  -- branch 63, taps 0..7
        x"0016", x"FFE6", x"001C", x"00D9", x"0020", x"FFE4", x"0017", x"FFEF",  -- branch 63, taps 8..15
        x"000B", x"FFFA", x"0003", x"0001", x"FFFF", x"0004", x"FFFE", x"FFFB"  -- branch 63, taps 16..23
    );

end package haifuraiya_coeffs_pkg;
