# =============================================================================
# repackage_no_coeff_file.tcl
# =============================================================================
#
# One-shot IP repackaging for the haifuraiya_channelizer_axi IP. Applies the
# Q1-B component.xml changes that accompany the source-level switch from
# `file_open` on a .hex file to a compiled-in VHDL coefficient package.
#
# Changes:
#   1. Remove COEFF_FILE modelParameter (no longer a generic on the entity)
#   2. Remove COEFF_FILE GUI parameter and its vendor extensions
#   3. Remove rtl/coeffs/haifuraiya_coeffs.hex from synthesis fileset
#      (no longer needed for synth; the .hex remains in the repo for the
#       simulation testbenches, which DO still use file_open)
#   4. Add rtl/channelizer/haifuraiya_coeffs_pkg.vhd to BOTH the synthesis
#      and simulation filesets, with fileType=vhdlSource. This file is
#      auto-generated by docs/polyphase_channelizer.ipynb -- generate it
#      and verify it exists BEFORE running this script.
#
# How to run (once, from repo root):
#   1. cd ~/brown/Mode-Dynamic-Transponder
#   2. Run docs/polyphase_channelizer.ipynb cells that emit the package, so
#      haifuraiya/rtl/channelizer/haifuraiya_coeffs_pkg.vhd exists
#   3. vivado -mode batch -source haifuraiya/scripts/repackage_no_coeff_file.tcl
#   4. Review the resulting diff of haifuraiya/component.xml
#   5. Commit the updated component.xml
#
# After this is done and committed, the script's job is complete. It does
# NOT run on every build. Keep it in git as documentation of the change.
# =============================================================================

# Path resolution from script location
set script_dir   [file dirname [file normalize [info script]]]
set ip_root      [file normalize "${script_dir}/.."]
set component_xml "${ip_root}/component.xml"
set pkg_file_rel  "rtl/channelizer/haifuraiya_coeffs_pkg.vhd"
set pkg_file_abs  "${ip_root}/${pkg_file_rel}"
set hex_file_rel  "rtl/coeffs/haifuraiya_coeffs.hex"

# Sanity checks
if {![file exists $component_xml]} {
    puts "ERROR: component.xml not found at $component_xml"
    return
}
if {![file exists $pkg_file_abs]} {
    puts "ERROR: $pkg_file_rel does not exist."
    puts "       Run the notebook cells in docs/polyphase_channelizer.ipynb"
    puts "       first to generate it, then re-run this script."
    return
}

puts "INFO: Opening IP at $component_xml"
catch {close_project}
ipx::open_core $component_xml

# -----------------------------------------------------------------------------
# 1. Remove COEFF_FILE modelParameter (entity generic)
# -----------------------------------------------------------------------------
set mp [ipx::get_user_parameters COEFF_FILE -of_objects [ipx::current_core]]
if {[llength $mp] > 0} {
    puts "INFO: Removing COEFF_FILE modelParameter / user parameter"
    ipx::remove_user_parameter COEFF_FILE [ipx::current_core]
} else {
    puts "INFO: COEFF_FILE user parameter not present -- already removed?"
}

set hdl_mp [ipx::get_hdl_parameters COEFF_FILE -of_objects [ipx::current_core]]
if {[llength $hdl_mp] > 0} {
    puts "INFO: Removing COEFF_FILE HDL parameter"
    ipx::remove_hdl_parameter COEFF_FILE [ipx::current_core]
} else {
    puts "INFO: COEFF_FILE HDL parameter not present -- already removed?"
}

# -----------------------------------------------------------------------------
# 2. Remove haifuraiya_coeffs.hex from synthesis fileset.
#    Leave it in the simulation fileset: testbenches still file_open it,
#    and xsim copies it to the sim working directory automatically.
# -----------------------------------------------------------------------------
set synth_fg [ipx::get_file_groups xilinx_anylanguagesynthesis \
                  -of_objects [ipx::current_core]]
if {[llength $synth_fg] > 0} {
    set hex_in_synth [ipx::get_files $hex_file_rel -of_objects $synth_fg]
    if {[llength $hex_in_synth] > 0} {
        puts "INFO: Removing $hex_file_rel from synthesis fileset"
        ipx::remove_file $hex_file_rel $synth_fg
    } else {
        puts "INFO: $hex_file_rel not present in synthesis fileset -- already removed?"
    }
} else {
    puts "WARNING: synthesis fileset not found"
}

# -----------------------------------------------------------------------------
# 3. Add haifuraiya_coeffs_pkg.vhd to synthesis and simulation filesets.
#    Type: vhdlSource (a standard, schema-valid file type, unlike "unknown").
# -----------------------------------------------------------------------------
foreach fg_name {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} {
    set fg [ipx::get_file_groups $fg_name -of_objects [ipx::current_core]]
    if {[llength $fg] == 0} {
        puts "WARNING: file group $fg_name not found, skipping"
        continue
    }
    set existing [ipx::get_files $pkg_file_rel -of_objects $fg]
    if {[llength $existing] > 0} {
        puts "INFO: $pkg_file_rel already in $fg_name -- skipping add"
    } else {
        puts "INFO: Adding $pkg_file_rel to $fg_name"
        ipx::add_file $pkg_file_rel $fg
        set f [ipx::get_files $pkg_file_rel -of_objects $fg]
        set_property type vhdlSource $f
    }
}

# -----------------------------------------------------------------------------
# 4. Reorder the package file so it appears EARLY in each fileset.
#    Packages must be analyzed before files that `use work.<pkg>.all`.
#    Vivado's BD synth usually handles this correctly via dependency
#    analysis, but ordering the fileset cooperatively avoids surprises.
# -----------------------------------------------------------------------------
foreach fg_name {xilinx_anylanguagesynthesis xilinx_anylanguagebehavioralsimulation} {
    set fg [ipx::get_file_groups $fg_name -of_objects [ipx::current_core]]
    if {[llength $fg] > 0} {
        catch {ipx::reorder_files -front $pkg_file_rel $fg} reorder_msg
        puts "INFO: Reordered $pkg_file_rel to front of $fg_name"
    }
}

# -----------------------------------------------------------------------------
# Save and report
# -----------------------------------------------------------------------------
ipx::create_xgui_files [ipx::current_core]
ipx::update_checksums  [ipx::current_core]
ipx::save_core         [ipx::current_core]

puts ""
puts "============================================================="
puts "  Repackaging complete."
puts ""
puts "  Changes applied to component.xml:"
puts "    - Removed COEFF_FILE generic (entity no longer has it)"
puts "    - Removed $hex_file_rel from synthesis fileset"
puts "    - Added $pkg_file_rel to synthesis + simulation filesets"
puts "    - Reordered package to front of both filesets"
puts ""
puts "  Next:"
puts "    1. Review: git diff haifuraiya/component.xml"
puts "    2. Commit if it looks right"
puts "    3. Run the integrated build: make haifuraiya-xsa-integrated"
puts "============================================================="
