-------------------------------------------------------------------------------
-- coeff_rom.vhd
-- Coefficient ROM for Polyphase Channelizer (Synthesis Version)
-------------------------------------------------------------------------------
-- Open Research Institute
-- Project: Polyphase Channelizer (MDT / Haifuraiya)
-- 
-- Description:
--   Stores prototype filter coefficients in fixed-point format for the 
--   polyphase filterbank. This version has hardcoded coefficients for
--   synthesis with GHDL (which doesn't support file I/O during synthesis).
--
--   For simulation or Vivado synthesis, use the file-based version.
--
-- Target: iCE40 UltraPlus (MDT)
--
-------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity coeff_rom is
    generic (
        N_CHANNELS      : positive := 4;
        TAPS_PER_BRANCH : positive := 16;
        COEFF_WIDTH     : positive := 16;
        ADDR_WIDTH      : positive := 6;
        COEFF_FILE      : string := "mdt_coeffs.hex"  -- Ignored in this version
    );
    port (
        clk     : in  std_logic;
        addr    : in  std_logic_vector(ADDR_WIDTH - 1 downto 0);
        coeff   : out std_logic_vector(COEFF_WIDTH - 1 downto 0)
    );
end entity coeff_rom;

architecture rtl of coeff_rom is

    constant ROM_DEPTH : positive := N_CHANNELS * TAPS_PER_BRANCH;
    
    type rom_type is array (0 to ROM_DEPTH - 1) of 
        std_logic_vector(COEFF_WIDTH - 1 downto 0);
    
    -- MDT coefficients (64 taps) from mdt_coeffs.hex
    -- Generated by polyphase_channelizer.ipynb
    constant rom : rom_type := (
        x"FF9F", x"FFF8", x"0036", x"0011",  -- 0-3
        x"000E", x"0047", x"FF8A", x"01C4",  -- 4-7
        x"0F73", x"FE08", x"014A", x"FF37",  -- 8-11
        x"00C3", x"FF97", x"008F", x"FFA0",  -- 12-15
        x"FF86", x"005E", x"FFC3", x"00A7",  -- 16-19
        x"FF3D", x"0174", x"FD97", x"0713",  -- 20-23
        x"0C42", x"FCBA", x"01F8", x"FED7",  -- 24-27
        x"00FA", x"FF7C", x"009D", x"FF78",  -- 28-31
        x"FF78", x"009D", x"FF7C", x"00FA",  -- 32-35
        x"FED7", x"01F8", x"FCBA", x"0C42",  -- 36-39
        x"0713", x"FD97", x"0174", x"FF3D",  -- 40-43
        x"00A7", x"FFC3", x"005E", x"FF86",  -- 44-47
        x"FFA0", x"008F", x"FF97", x"00C3",  -- 48-51
        x"FF37", x"014A", x"FE08", x"0F73",  -- 52-55
        x"01C4", x"FF8A", x"0047", x"000E",  -- 56-59
        x"0011", x"0036", x"FFF8", x"FF9F"   -- 60-63
    );
    
    signal coeff_reg : std_logic_vector(COEFF_WIDTH - 1 downto 0);

begin

    process(clk)
    begin
        if rising_edge(clk) then
            coeff_reg <= rom(to_integer(unsigned(addr)));
        end if;
    end process;
    
    coeff <= coeff_reg;

end architecture rtl;
