#!/bin/bash
# copy_to_keroppi.sh
#
# Copy everything needed for JTAG boot from mymelody (build host) to
# keroppi (lab VM connected to ZCU102). Splits artifacts into two
# destinations:
#   - JTAG-load files + boot scripts → /tmp/abraxas3d-yocto-boot/
#   - TFTP-served files (kernel/dtb/initramfs) → /tftpboot/abraxas3d-yocto/
#
# JTAG-load files include:
#   - PMU firmware, FSBL, ATF, U-Boot (Yocto build outputs)
#   - boot.scr (generated by make_boot_scr.sh)
#   - zcu102_jtag_boot.tcl, run_jtag_boot.sh (boot orchestration)
#
# Assumes:
#   - SSH key-based access to abraxas3d@keroppi works (no password prompts)
#   - You're a member of the 'tftp' group on keroppi (per lab doc)
#   - boot.scr exists in this script's directory (run make_boot_scr.sh first)
#
# Usage:
#   ./copy_to_keroppi.sh

set -euo pipefail

# --- Locate this script's directory (for finding boot.scr + .tcl + .sh) ---
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# --- Source paths on mymelody ---
DEPLOY_DIR="$HOME/yocto/haifuraiya/build/tmp/deploy/images/zcu102-zynqmp"
BOOT_SCR="${SCRIPT_DIR}/boot.scr"
JTAG_TCL="${SCRIPT_DIR}/zcu102_jtag_boot.tcl"
RUN_SH="${SCRIPT_DIR}/run_jtag_boot.sh"

# --- Destination on keroppi ---
KEROPPI_USER="abraxas3d"
KEROPPI_HOST="keroppi"
JTAG_DIR="/tmp/abraxas3d-yocto-boot"
TFTP_DIR="/tftpboot/abraxas3d-yocto"

# --- Sanity checks ---
if [ ! -f "$BOOT_SCR" ]; then
    echo "ERROR: boot.scr not found at $BOOT_SCR" >&2
    echo "       Run ./make_boot_scr.sh first to generate it from boot-script.txt" >&2
    exit 1
fi

if [ ! -d "$DEPLOY_DIR" ]; then
    echo "ERROR: Yocto deploy directory not found: $DEPLOY_DIR" >&2
    echo "       Did the bitbake build complete successfully?" >&2
    exit 1
fi

echo "=== Creating destination directories on keroppi ==="
ssh ${KEROPPI_USER}@${KEROPPI_HOST} "
    mkdir -p ${JTAG_DIR}
    mkdir -p ${TFTP_DIR}
    chmod 755 ${JTAG_DIR} ${TFTP_DIR}
"

echo ""
echo "=== Copying Yocto-built JTAG-load files (FSBL/PMU/ATF/U-Boot) ==="
# These are loaded into RAM via xsdb during JTAG boot

ADI_BITSTREAM="${HOME}/brown/Mode-Dynamic-Transponder/haifuraiya/third_party/hdl/projects/adrv9001/zcu102/adrv9001_zcu102.runs/impl_1/system_top.bit"

scp ${DEPLOY_DIR}/fsbl-zcu102-zynqmp.elf \
    ${DEPLOY_DIR}/pmu-firmware-zcu102-zynqmp.elf \
    ${DEPLOY_DIR}/arm-trusted-firmware.bin \
    ${DEPLOY_DIR}/u-boot.elf \
    ${ADI_BITSTREAM} \
    ${KEROPPI_USER}@${KEROPPI_HOST}:${JTAG_DIR}/

echo ""
echo "=== Copying boot.scr (loaded to 0x20000000 by xsdb) ==="
# boot.scr is the U-Boot script that runs automatically at autoboot.
# Sets static IPs, fetches kernel/dtb/initramfs via TFTP, calls booti.
scp ${BOOT_SCR} ${KEROPPI_USER}@${KEROPPI_HOST}:${JTAG_DIR}/

echo ""
echo "=== Copying JTAG boot orchestration scripts ==="
# These run on keroppi to invoke xsdb with the right sequence.
scp ${JTAG_TCL} ${RUN_SH} ${KEROPPI_USER}@${KEROPPI_HOST}:${JTAG_DIR}/
ssh ${KEROPPI_USER}@${KEROPPI_HOST} "chmod +x ${JTAG_DIR}/run_jtag_boot.sh"

echo ""
echo "=== Copying TFTP-served files (kernel/dtb/initramfs) ==="
# These are fetched by U-Boot from the TFTP server (keroppi) into RAM
scp ${DEPLOY_DIR}/Image \
    ${DEPLOY_DIR}/system.dtb \
    ${DEPLOY_DIR}/petalinux-image-minimal-zcu102-zynqmp.cpio.gz.u-boot \
    ${KEROPPI_USER}@${KEROPPI_HOST}:${TFTP_DIR}/

echo ""
echo "=== Creating short-name symlinks on keroppi (TFTP-friendly) ==="
ssh ${KEROPPI_USER}@${KEROPPI_HOST} "
    cd ${TFTP_DIR}
    ln -sf petalinux-image-minimal-zcu102-zynqmp.cpio.gz.u-boot initramfs.cpio.gz.u-boot
    ls -la
"

echo ""
echo "=== Copy complete ==="
echo "JTAG-load files + scripts in:  keroppi:${JTAG_DIR}"
echo "TFTP-served files:             keroppi:${TFTP_DIR}"
echo ""
echo "Next: ssh to keroppi, power-cycle ZCU102, run:"
echo "  cd ${JTAG_DIR} && ./run_jtag_boot.sh"
echo ""
echo "U-Boot autoboot will find boot.scr at 0x20000000 and TFTP-boot Linux."
