-- tb_channel_eq.vhd  -- self-checking testbench for channel_eq
-- Drives eq_input.txt (chan, i, q per line) and compares outputs to eq_expected.txt
-- (generated by channel_eq.py apply_eq_fixed). Reports PASS/FAIL.

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use std.textio.all;

entity tb_channel_eq is
end entity;

architecture sim of tb_channel_eq is
  signal clk       : std_logic := '0';
  signal rst       : std_logic := '1';
  signal in_valid  : std_logic := '0';
  signal in_chan   : unsigned(5 downto 0) := (others => '0');
  signal in_i, in_q : signed(15 downto 0) := (others => '0');
  signal out_valid : std_logic;
  signal out_chan  : unsigned(5 downto 0);
  signal out_i, out_q : signed(15 downto 0);
  signal inputs_done : boolean := false;
  signal errors, checked : integer := 0;
begin
  clk <= not clk after 5 ns;

  dut : entity work.channel_eq
    port map (clk => clk, rst => rst, in_valid => in_valid, in_chan => in_chan,
              in_i => in_i, in_q => in_q, out_valid => out_valid,
              out_chan => out_chan, out_i => out_i, out_q => out_q);

  stim : process
    file fin : text open read_mode is "eq_input.txt";
    variable L : line;
    variable vc, vi, vq : integer;
  begin
    rst <= '1'; wait until rising_edge(clk); wait until rising_edge(clk);
    rst <= '0'; wait until rising_edge(clk);
    while not endfile(fin) loop
      readline(fin, L); read(L, vc); read(L, vi); read(L, vq);
      in_chan <= to_unsigned(vc, 6);
      in_i <= to_signed(vi, 16); in_q <= to_signed(vq, 16);
      in_valid <= '1';
      wait until rising_edge(clk);
    end loop;
    in_valid <= '0';
    for k in 0 to 15 loop wait until rising_edge(clk); end loop;
    inputs_done <= true; wait;
  end process;

  chk : process
    file fexp : text open read_mode is "eq_expected.txt";
    variable L : line;
    variable ei, eq : integer;
  begin
    wait until rising_edge(clk);
    if out_valid = '1' then
      readline(fexp, L); read(L, ei); read(L, eq);
      if to_integer(out_i) /= ei or to_integer(out_q) /= eq then
        errors <= errors + 1;
        report "mismatch at " & integer'image(checked) & ": got (" &
          integer'image(to_integer(out_i)) & "," & integer'image(to_integer(out_q)) &
          ") exp (" & integer'image(ei) & "," & integer'image(eq) & ")" severity warning;
      end if;
      checked <= checked + 1;
    end if;
  end process;

  finish_proc : process
  begin
    wait until inputs_done; wait for 1 ns;
    report "checked " & integer'image(checked) & " outputs, " &
      integer'image(errors) & " mismatches" severity note;
    if errors = 0 then
      report "PASS: channel_eq is bit-exact to the golden model" severity note;
    else
      report "FAIL" severity error;
    end if;
    std.env.stop;
  end process;
end architecture sim;
