-- tb_halfband_decimator.vhd
-- Self-checking testbench for halfband_decimator.
-- Drives tb_input.txt (one 20 Msps I,Q sample per line) and compares the decimated
-- output stream, in emit order, against tb_expected.txt (generated by the golden
-- model, halfband_decimator.py / gen_vectors.py). Reports per-sample mismatches and
-- a final PASS/FAIL.
--
--   xvhdl --2008 halfband_taps_pkg.vhd halfband_decimator.vhd tb_halfband_decimator.vhd
--   xelab --debug typical tb_halfband_decimator -s hb_sim
--   xsim hb_sim --runall
--
-- Note: in_valid is held high every clock here (continuous stream). The DUT keys all
-- timing off in_valid, so it is also correct with gaps; add gaps to stress that path.

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use std.textio.all;

entity tb_halfband_decimator is
end entity;

architecture sim of tb_halfband_decimator is
  signal clk       : std_logic := '0';
  signal rst       : std_logic := '1';
  signal in_valid  : std_logic := '0';
  signal in_i      : signed(15 downto 0) := (others => '0');
  signal in_q      : signed(15 downto 0) := (others => '0');
  signal out_valid : std_logic;
  signal out_i     : signed(15 downto 0);
  signal out_q     : signed(15 downto 0);

  signal inputs_done : boolean := false;
  signal errors      : integer := 0;
  signal checked     : integer := 0;

begin
  clk <= not clk after 5 ns;            -- 100 MHz

  dut : entity work.halfband_decimator
    port map (clk => clk, rst => rst,
              in_valid => in_valid, in_i => in_i, in_q => in_q,
              out_valid => out_valid, out_i => out_i, out_q => out_q);

  -- drive: reset, then one input sample per clock from tb_input.txt
  stim : process
    file fin     : text open read_mode is "tb_input.txt";
    variable L   : line;
    variable vi, vq : integer;
  begin
    rst <= '1'; in_valid <= '0';
    wait until rising_edge(clk); wait until rising_edge(clk);
    rst <= '0';
    wait until rising_edge(clk);

    while not endfile(fin) loop
      readline(fin, L);
      read(L, vi); read(L, vq);
      in_i     <= to_signed(vi, 16);
      in_q     <= to_signed(vq, 16);
      in_valid <= '1';
      wait until rising_edge(clk);
    end loop;
    in_valid <= '0';

    -- drain the pipeline
    for k in 0 to 31 loop
      wait until rising_edge(clk);
    end loop;
    inputs_done <= true;
    wait;
  end process;

  -- check: each out_valid pops the next expected line and compares
  chk : process
    file fexp    : text open read_mode is "tb_expected.txt";
    variable L   : line;
    variable ei, eq : integer;
  begin
    wait until rising_edge(clk);
    if out_valid = '1' then
      if endfile(fexp) then
        report "more outputs than expected!" severity error;
        errors <= errors + 1;
      else
        readline(fexp, L);
        read(L, ei); read(L, eq);
        if to_integer(out_i) /= ei or to_integer(out_q) /= eq then
          errors <= errors + 1;
          report "mismatch at output " & integer'image(checked) &
                 ": got (" & integer'image(to_integer(out_i)) & "," &
                 integer'image(to_integer(out_q)) & ") exp (" &
                 integer'image(ei) & "," & integer'image(eq) & ")"
                 severity warning;
        end if;
        checked <= checked + 1;
      end if;
    end if;
  end process;

  -- finish
  finish_proc : process
  begin
    wait until inputs_done;
    wait for 1 ns;
    report "checked " & integer'image(checked) & " outputs, " &
           integer'image(errors) & " mismatches" severity note;
    if errors = 0 then
      report "PASS: decimator is bit-exact to the golden model" severity note;
    else
      report "FAIL" severity error;
    end if;
    std.env.stop;
  end process;

end architecture sim;
